In [9]:
import numpy as np
import tensorflow as tf

In [10]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])

print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [11]:
#2D Array
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t.ndim) # rank
print(t.shape) # shape

2
(4, 3)


In [14]:
#shape
sess = tf.InteractiveSession()
t= tf.constant([1,2,3,4])
print(tf.shape(t).eval())

[4]


In [15]:
#Rank [] 몇개 있는지
t = tf.constant([[1,2],
                [3,4]])
tf.shape(t).eval()

array([2, 2], dtype=int32)

In [21]:
#Axis
t = tf.constant([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                [[13,14,15,16],[17,18,19,20],[21,22,23,24]]]])
tf.shape(t).eval()
# rank =4, shape ?,?,?,? 그러므로  shape (1,2,3,4)
#Axis rank 4 그러므로 4

array([1, 2, 3, 4], dtype=int32)

In [25]:
# Matmul vs multiply
matrix1 = tf.constant([[1.,2.],[3.,4.]]) #(2,2)
matrix2 = tf.constant([[1.],[2.]]) #(2,1)
print("Metrix 1 shape", matrix1.shape)
print("Metrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

#(Matrix1 * Matrix2).eval()#값이 다름 조심할 것


Metrix 1 shape (2, 2)
Metrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [26]:
#Operations between the same shapes
matrix1 = tf.constant([[3.,3.]])
matrix2 = tf.constant([[2.,2.]])
(matrix1 + matrix2).eval()

array([[5., 5.]], dtype=float32)

In [27]:
#BroadCasting ->shape이 달라도 연산할 수 있게 해줌.

In [28]:
matrix1 = tf.constant([[1.,2.,]])
matrix2 = tf.constant(3.)
(matrix1+matrix2).eval()

array([[4., 5.]], dtype=float32)

In [29]:
matrix1 = tf.constant([[1.,2.,]])
matrix2 = tf.constant([3.,4.])
(matrix1 + matrix2).eval()

array([[4., 6.]], dtype=float32)

In [30]:
matrix1 = tf.constant([[1.,2.]])
matrix2 = tf.constant([[3.],[4.]])
(matrix1+matrix2).eval()

array([[4., 5.],
       [5., 6.]], dtype=float32)

In [32]:
#Reduce mean
tf.reduce_mean([1,2], axis=0).eval()

1

In [33]:
x = [[1.,2.],
    [3.,4.]]

tf.reduce_mean(x).eval()

2.5

In [34]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [35]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [36]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

In [37]:
tf.reduce_sum(x).eval()

10.0

In [38]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [39]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [40]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

In [41]:
#Argmax
x=[[0,1,2],
  [2,1,0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [42]:
tf.argmax(x, axis=1).eval()

array([2, 0])

In [43]:
tf.argmax(x, axis=-1).eval()

array([2, 0])

In [44]:
#reshape 가장 많이 사용함
t = np.array([[[0,1,2],
              [3,4,5,]],
              
              [[6,7,8],
              [9,10,11]]])
t.shape

(2, 2, 3)

In [45]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
tf.reshape(t, shape=[-1,1,3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [47]:
#Reshape(squeeze, expand)
tf.squeeze([[0],[1],[2]]).eval()

array([0, 1, 2], dtype=int32)

In [48]:
tf.expand_dims([0,1,2],1).eval()

array([[0],
       [1],
       [2]], dtype=int32)

In [53]:
#One hot
tf.one_hot([[0],[1],[2],[0]], depth=3).eval()
# one_hot 을 쓰면 rank가 1 올라감 [[ ]] -> [[[ ]]]

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [54]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1,3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [56]:
#Casting
tf.cast([1.8,2.2,3.3,4.9], tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [57]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

In [61]:
#Stack
x = [1,2]
y = [2,5]
z = [3,6]

#Pack along first dim.
tf.stack([x,y,z]).eval()

array([[1, 2],
       [2, 5],
       [3, 6]], dtype=int32)

In [62]:
tf.stack([x,y,z], axis=1).eval()

array([[1, 2, 3],
       [2, 5, 6]], dtype=int32)

In [63]:
#Ones and Zeros Like
x = [[0,1,2],
    [2,1,0]]
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [64]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [66]:
# Zip
for x,y in zip([1,2,3],[4,5,6]):
    print(x,y)

1 4
2 5
3 6


In [67]:
for x, y, z in zip([1,2,3],[4,5,6],[7,8,9]):
    print(x,y,z)

1 4 7
2 5 8
3 6 9
