In [4]:
import numpy as np
import tensorflow as tf

In [7]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [9]:
import numpy as np
import tensorflow as tf
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

#Placeholder for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name= 'weight')
b = tf.Variable(tf.random_normal([1]), name= 'bias')

#hypothesis
hypothesis = tf.matmul(X, W) + b

#Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

#launch the graph in a session
sess = tf.Session()
#Initialize global variable in the graph
sess.run(tf.global_variables_initializer())
# Set up feed_dict variables inside the loop
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val,
                 "\nPrediction:\n", hy_val)
        
print("Your score will be ", sess.run(hypothesis,
            feed_dict={X: [[100,70,101]]}))
print("Other scores will be ", sess.run(hypothesis,
            feed_dict={X: [[60,70,110],[90, 100, 80]]}))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
0 Cost:  5620.36 
Prediction:
 [[ 83.74415 ]
 [101.97009 ]
 [ 99.92202 ]
 [107.23447 ]
 [ 79.41186 ]
 [ 56.2594  ]
 [ 77.54329 ]
 [ 53.63449 ]
 [ 93.66785 ]
 [ 83.37192 ]
 [ 76.73364 ]
 [ 75.636154]
 [104.88552 ]
 [ 89.55868 ]
 [ 77.921455]
 [101.83949 ]
 [ 87.63305 ]
 [ 91.74488 ]
 [100.043365]
 [ 89.085815]
 [ 91.68233 ]
 [ 9

340 Cost:  28.444653 
Prediction:
 [[153.69896]
 [186.37488]
 [182.89119]
 [197.94098]
 [143.57903]
 [104.14052]
 [145.86487]
 [104.8679 ]
 [173.04947]
 [157.69446]
 [142.29877]
 [140.56142]
 [190.25412]
 [160.05016]
 [146.6441 ]
 [187.79117]
 [154.44652]
 [173.88121]
 [181.3248 ]
 [161.84113]
 [171.7235 ]
 [173.52852]
 [163.94019]
 [157.97484]
 [193.48334]]
350 Cost:  28.28838 
Prediction:
 [[153.69052]
 [186.37308]
 [182.88434]
 [197.94302]
 [143.57187]
 [104.1509 ]
 [145.87823]
 [104.89408]
 [173.06134]
 [157.7272 ]
 [142.30435]
 [140.57425]
 [190.23744]
 [160.02324]
 [146.65982]
 [187.79764]
 [154.41191]
 [173.90135]
 [181.3061 ]
 [161.82523]
 [171.73697]
 [173.5356 ]
 [163.9496 ]
 [157.94402]
 [193.47568]]
360 Cost:  28.133274 
Prediction:
 [[153.68217]
 [186.37126]
 [182.87755]
 [197.94508]
 [143.56473]
 [104.16122]
 [145.89156]
 [104.92018]
 [173.07314]
 [157.75981]
 [142.3099 ]
 [140.58699]
 [190.22084]
 [159.99641]
 [146.67549]
 [187.8041 ]
 [154.37743]
 [173.9214 ]
 [181.2874

860 Cost:  21.690777 
Prediction:
 [[153.32256]
 [186.27316]
 [182.57349]
 [198.04288]
 [143.21901]
 [104.60734]
 [146.5091 ]
 [106.1291 ]
 [173.5831 ]
 [159.21034]
 [142.56386]
 [141.14935]
 [189.47253]
 [158.78238]
 [147.39326]
 [188.08275]
 [152.80367]
 [174.85626]
 [180.45439]
 [161.10577]
 [172.36984]
 [173.84828]
 [164.39891]
 [156.54155]
 [193.11133]]
870 Cost:  21.584797 
Prediction:
 [[153.31642 ]
 [186.27106 ]
 [182.56805 ]
 [198.04472 ]
 [143.21233 ]
 [104.614975]
 [146.52052 ]
 [106.15146 ]
 [173.59186 ]
 [159.23602 ]
 [142.56848 ]
 [141.15921 ]
 [189.45908 ]
 [158.76047 ]
 [147.40637 ]
 [188.08751 ]
 [152.775   ]
 [174.87366 ]
 [180.43954 ]
 [161.0933  ]
 [172.38126 ]
 [173.85355 ]
 [164.40712 ]
 [156.51712 ]
 [193.10466 ]]
880 Cost:  21.479582 
Prediction:
 [[153.31035]
 [186.26897]
 [182.56268]
 [198.04657]
 [143.20566]
 [104.62259]
 [146.53194]
 [106.17377]
 [173.60052]
 [159.2616 ]
 [142.5731 ]
 [141.16902]
 [189.44571]
 [158.73863]
 [147.41946]
 [188.09229]
 [152.7464

1390 Cost:  17.017706 
Prediction:
 [[153.04645 ]
 [186.15776 ]
 [182.31778 ]
 [198.13586 ]
 [142.8782  ]
 [104.95467 ]
 [147.07065 ]
 [107.226715]
 [173.97946 ]
 [160.41815 ]
 [142.78777 ]
 [141.60812 ]
 [188.83095 ]
 [157.73131 ]
 [148.03084 ]
 [188.3     ]
 [151.41829 ]
 [175.71494 ]
 [179.75027 ]
 [160.51984 ]
 [172.92722 ]
 [174.08919 ]
 [164.80594 ]
 [155.38646 ]
 [192.78226 ]]
1400 Cost:  16.945663 
Prediction:
 [[153.04211 ]
 [186.1555  ]
 [182.3135  ]
 [198.13753 ]
 [142.87204 ]
 [104.9602  ]
 [147.08043 ]
 [107.245804]
 [173.98575 ]
 [160.43817 ]
 [142.7916  ]
 [141.61562 ]
 [188.82013 ]
 [157.71349 ]
 [148.04181 ]
 [188.30344 ]
 [151.39459 ]
 [175.72995 ]
 [179.7385  ]
 [160.51012 ]
 [172.93686 ]
 [174.09305 ]
 [164.81308 ]
 [155.3672  ]
 [192.77649 ]]
1410 Cost:  16.874115 
Prediction:
 [[153.03781]
 [186.15327]
 [182.30927]
 [198.13919]
 [142.86588]
 [104.96569]
 [147.09016]
 [107.26485]
 [173.992  ]
 [160.45808]
 [142.79541]
 [141.6231 ]
 [188.80937]
 [157.69574]
 [148.05

1910 Cost:  13.87518 
Prediction:
 [[152.85583]
 [186.03943]
 [182.11972]
 [198.21738]
 [142.57019]
 [105.19914]
 [147.54268]
 [108.148  ]
 [174.25774]
 [161.34283]
 [142.97023]
 [141.9509 ]
 [188.32327]
 [156.89081]
 [148.55449]
 [188.45319]
 [150.29099]
 [176.44373]
 [179.20193]
 [160.0712 ]
 [173.39088]
 [174.2615 ]
 [165.15381]
 [154.4907 ]
 [192.50182]]
1920 Cost:  13.8253565 
Prediction:
 [[152.85281]
 [186.03714]
 [182.11636]
 [198.21887]
 [142.56454]
 [105.20308]
 [147.55107]
 [108.16437]
 [174.2622 ]
 [161.35847]
 [142.97343]
 [141.95662]
 [188.31454]
 [156.87625]
 [148.56369]
 [188.45566]
 [150.27127]
 [176.45676]
 [179.19257]
 [160.06361]
 [173.3991 ]
 [174.2643 ]
 [165.16003]
 [154.47545]
 [192.49681]]
1930 Cost:  13.775841 
Prediction:
 [[152.84981]
 [186.03485]
 [182.11299]
 [198.22035]
 [142.55887]
 [105.20696]
 [147.55943]
 [108.18069]
 [174.26663]
 [161.37405]
 [142.97661]
 [141.9623 ]
 [188.30583]
 [156.86176]
 [148.57286]
 [188.45811]
 [150.25162]
 [176.46974]
 [179.

In [10]:
#tf.train.batch
# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

sess = tf.Session()

#start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    
coord.request_stop()
coord.join(threads)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [2]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name= 'filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
#decoded result.
record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

#collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholder for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

#hypothesis
hypothesis = tf.matmul(X, W) + b

#simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

#Launch the graph in a session
sess = tf.Session()
#Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

#Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord = coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val,
             "\nPrediction:\n", hy_val)
       
coord.request_stop()
coord.join(threads)

0 Cost:  32856.96 
Prediction:
 [[-16.489151]
 [-30.802536]
 [-24.732582]
 [-25.777975]
 [-27.293478]
 [-19.84664 ]
 [-14.665371]
 [ -4.020687]
 [-30.03865 ]
 [-26.399767]]
10 Cost:  40.91384 
Prediction:
 [[157.6051 ]
 [178.51453]
 [181.47308]
 [198.80562]
 [132.35449]
 [ 97.87909]
 [153.43799]
 [120.59138]
 [165.61188]
 [154.8487 ]]
20 Cost:  37.563866 
Prediction:
 [[158.76146 ]
 [179.94257 ]
 [182.86021 ]
 [200.31943 ]
 [133.45055 ]
 [ 98.696434]
 [154.56502 ]
 [121.41724 ]
 [166.95917 ]
 [156.10693 ]]
30 Cost:  37.338917 
Prediction:
 [[158.75085]
 [179.9677 ]
 [182.8652 ]
 [200.32793]
 [133.4766 ]
 [ 98.72477]
 [154.56529]
 [121.40779]
 [166.99518]
 [156.1504 ]]
40 Cost:  37.126472 
Prediction:
 [[158.73244]
 [179.98332]
 [182.86089]
 [200.32626]
 [133.49538]
 [ 98.74768]
 [154.55797]
 [121.39273]
 [167.02222]
 [156.18552]]
50 Cost:  36.915607 
Prediction:
 [[158.71404 ]
 [179.99878 ]
 [182.85654 ]
 [200.32451 ]
 [133.51402 ]
 [ 98.77047 ]
 [154.55057 ]
 [121.377655]
 [167.0491  

490 Cost:  28.947224 
Prediction:
 [[157.96925 ]
 [180.63232 ]
 [182.68367 ]
 [200.25117 ]
 [134.28214 ]
 [ 99.69206 ]
 [154.23695 ]
 [120.738396]
 [168.1358  ]
 [157.61714 ]]
500 Cost:  28.792725 
Prediction:
 [[157.9537 ]
 [180.64568]
 [182.68015]
 [200.24957]
 [134.29845]
 [ 99.71127]
 [154.23007]
 [120.72441]
 [168.15845]
 [157.64592]]
510 Cost:  28.639233 
Prediction:
 [[157.93822]
 [180.65901]
 [182.67662]
 [200.24796]
 [134.31471]
 [ 99.73041]
 [154.22322]
 [120.71045]
 [168.18102]
 [157.67458]]
520 Cost:  28.486822 
Prediction:
 [[157.92279 ]
 [180.67227 ]
 [182.67313 ]
 [200.24635 ]
 [134.33092 ]
 [ 99.749466]
 [154.21635 ]
 [120.69651 ]
 [168.20349 ]
 [157.70312 ]]
530 Cost:  28.335455 
Prediction:
 [[157.90741]
 [180.6855 ]
 [182.66963]
 [200.24475]
 [134.34706]
 [ 99.76846]
 [154.20949]
 [120.68259]
 [168.22588]
 [157.73152]]
540 Cost:  28.185099 
Prediction:
 [[157.8921 ]
 [180.6987 ]
 [182.66618]
 [200.24316]
 [134.36319]
 [ 99.78738]
 [154.20267]
 [120.66871]
 [168.2482 

990 Cost:  22.372417 
Prediction:
 [[157.25812]
 [181.25008]
 [182.5259 ]
 [200.17406]
 [135.04088]
 [100.569  ]
 [153.90625]
 [120.06817]
 [169.17007]
 [158.91563]]
1000 Cost:  22.262203 
Prediction:
 [[157.24521 ]
 [181.26147 ]
 [182.52312 ]
 [200.1726  ]
 [135.05496 ]
 [100.584915]
 [153.89993 ]
 [120.05537 ]
 [169.18884 ]
 [158.93887 ]]
1010 Cost:  22.152655 
Prediction:
 [[157.23232]
 [181.2728 ]
 [182.52034]
 [200.17113]
 [135.06897]
 [100.60077]
 [153.8936 ]
 [120.04259]
 [169.20757]
 [158.96204]]
1020 Cost:  22.0439 
Prediction:
 [[157.21947]
 [181.28407]
 [182.51756]
 [200.16966]
 [135.08295]
 [100.61658]
 [153.88728]
 [120.02983]
 [169.22618]
 [158.98508]]
1030 Cost:  21.935818 
Prediction:
 [[157.20668]
 [181.29533]
 [182.5148 ]
 [200.16818]
 [135.09688]
 [100.63231]
 [153.88098]
 [120.01709]
 [169.24475]
 [159.00803]]
1040 Cost:  21.828455 
Prediction:
 [[157.19392]
 [181.30655]
 [182.51205]
 [200.1667 ]
 [135.11076]
 [100.64799]
 [153.87468]
 [120.00438]
 [169.26323]
 [159

1470 Cost:  17.823929 
Prediction:
 [[156.68758 ]
 [181.7567  ]
 [182.40555 ]
 [200.10622 ]
 [135.67123 ]
 [101.26998 ]
 [153.6143  ]
 [119.479454]
 [169.99701 ]
 [159.92743 ]]
1480 Cost:  17.743595 
Prediction:
 [[156.67671]
 [181.76643]
 [182.4033 ]
 [200.10484]
 [135.68344]
 [101.2833 ]
 [153.60847]
 [119.46775]
 [170.01271]
 [159.9464 ]]
1490 Cost:  17.663776 
Prediction:
 [[156.6659  ]
 [181.77617 ]
 [182.4011  ]
 [200.10352 ]
 [135.69562 ]
 [101.29657 ]
 [153.60268 ]
 [119.456055]
 [170.02838 ]
 [159.9653  ]]
1500 Cost:  17.584454 
Prediction:
 [[156.6551 ]
 [181.78587]
 [182.39888]
 [200.10216]
 [135.70778]
 [101.3098 ]
 [153.59688]
 [119.44438]
 [170.04398]
 [159.98409]]
1510 Cost:  17.50572 
Prediction:
 [[156.64438 ]
 [181.79553 ]
 [182.3967  ]
 [200.10085 ]
 [135.71988 ]
 [101.322975]
 [153.5911  ]
 [119.43275 ]
 [170.05952 ]
 [160.00284 ]]
1520 Cost:  17.427425 
Prediction:
 [[156.63367]
 [181.80516]
 [182.3945 ]
 [200.0995 ]
 [135.73196]
 [101.3361 ]
 [153.58531]
 [119.421

1960 Cost:  14.439081 
Prediction:
 [[156.19864 ]
 [182.20024 ]
 [182.30774 ]
 [200.04295 ]
 [136.22992 ]
 [101.868515]
 [153.34134 ]
 [118.93131 ]
 [170.70325 ]
 [160.76894 ]]
1970 Cost:  14.380486 
Prediction:
 [[156.18953]
 [182.2086 ]
 [182.30597]
 [200.04173]
 [136.24051]
 [101.87965]
 [153.33603]
 [118.92066]
 [170.7164 ]
 [160.78438]]
1980 Cost:  14.322233 
Prediction:
 [[156.18042]
 [182.21693]
 [182.30418]
 [200.04048]
 [136.25105]
 [101.89074]
 [153.3307 ]
 [118.91003]
 [170.72948]
 [160.79973]]
1990 Cost:  14.264379 
Prediction:
 [[156.17139 ]
 [182.22525 ]
 [182.30244 ]
 [200.03928 ]
 [136.26161 ]
 [101.901794]
 [153.32542 ]
 [118.89943 ]
 [170.74254 ]
 [160.81505 ]]
2000 Cost:  14.206897 
Prediction:
 [[156.16237]
 [182.23354]
 [182.30069]
 [200.03804]
 [136.27211]
 [101.9128 ]
 [153.32014]
 [118.88884]
 [170.75552]
 [160.83028]]
