In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [3]:
# Evaluation our model using this test dataset
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

In [6]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))


hypothesis = tf.nn.softmax(tf.matmul(X, W)+ b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

#correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

#launch graph
with tf.Session() as sess:
    #Initializer Tensorflow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        
    #predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    #calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 1.5490806 [[ 0.42484674 -0.75429     1.3475913 ]
 [-0.25072178 -2.0662627  -0.42356795]
 [-1.1931999   0.85545063 -1.9483316 ]]
1 1.3673959 [[ 0.4146785  -0.7656475   1.369117  ]
 [-0.27327487 -2.1008863  -0.36639112]
 [-1.1850126   0.7871984  -1.8882667 ]]
2 1.2465689 [[ 0.40207836 -0.77048564  1.3865553 ]
 [-0.31484625 -2.0995584  -0.32614785]
 [-1.1992009   0.75509965 -1.8419796 ]]
3 1.1870706 [[ 0.39510643 -0.7756612   1.3987027 ]
 [-0.3273905  -2.1017325  -0.3114294 ]
 [-1.1891007   0.71967435 -1.8166544 ]]
4 1.1651793 [[ 0.38799    -0.7777901   1.4079481 ]
 [-0.3418152  -2.0873425  -0.3113948 ]
 [-1.1830155   0.70118505 -1.8042504 ]]
5 1.1538374 [[ 0.382196   -0.77983534  1.4157873 ]
 [-0.34902927 -2.0729551  -0.31856805]
 [-1.1709253   0.68283975 -1.7979953 ]]
6 1.1436688 [[ 0.37605175 -0.7813342   1.4234304 ]
 [-0.3584458  -2.0556638  -0.3264428 ]
 [-1.1611917   0.6675629  -1.7924521 ]]
7 1.1336612 [[ 0.3702159  -0.78296095  1.4308931 ]
 [-0.36623445 -2.0393107  -0.3350073 ]


In [7]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))


hypothesis = tf.nn.softmax(tf.matmul(X, W)+ b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)

#correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

#launch graph
with tf.Session() as sess:
    #Initializer Tensorflow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        
    #predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    #calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 11.155349 [[ 1.1386735  -0.32635516  0.29629743]
 [ 3.7007387   2.370187   -3.43435   ]
 [ 2.88232     1.2249113  -4.190525  ]]
1 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
2 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
3 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
4 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
5 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
6 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
7 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
8 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
9 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
10 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
11 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
12 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
13 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
14 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
15 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
16 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
17 nan [[nan nan nan]
 [nan nan

199 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
200 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
Prediction: [0 0 0]
Accuracy:  0.0


In [18]:
from sklearn.preprocessing import MinMaxScaler

    
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
              [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
              [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
              [816, 820.958984, 1008100, 815.48999, 819.23999],
              [819.359985, 823, 1188100, 818.469971, 818.97998],
              [819, 823, 1198100, 816, 820.450012],
              [811.70012, 815.25, 1098100, 809.780029, 813.669983],
              [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
xy=MinMaxScaler().fit_transform(xy)
print(xy)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

#placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
#minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436628 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
0 Cost:  1.4081463 
Prediction:
 [[ 0.41011906]
 [-0.51539546]
 [-0.5738869 ]
 [-0.6984006 ]
 [-0.493904  ]
 [-0.5998143 ]
 [-1.1219143 ]
 [-1.5875452 ]]
1 Cost:  1.4080561 
Prediction:
 [[ 0.41017067]
 [-0.51534235]
 [-0.57384235]
 [-0.6983658 ]
 [-0.49386328]
 [-0.5997748 ]
 [-1.1218859 ]
 [-1.5875163 ]]
2 Cost:  1.4079659 
Prediction:
 [[ 0.4102224 ]
 [-0.5152891 ]
 [-0.57379776]
 [-0.6983309 ]
 [-0.49382257]
 [-0.59973526]
 [-1.1218574 ]
 [-1.5874873 ]]
3 Cost:  1.4078758 
Prediction:
 [[ 0.41027403]
 [-0.515236  ]
 [-0.57375

87 Cost:  1.4003203 
Prediction:
 [[ 0.41460788]
 [-0.51077485]
 [-0.5700153 ]
 [-0.6953726 ]
 [-0.49036646]
 [-0.59637713]
 [-1.1194429 ]
 [-1.5850303 ]]
88 Cost:  1.4002306 
Prediction:
 [[ 0.41465938]
 [-0.51072174]
 [-0.56997085]
 [-0.69533783]
 [-0.4903258 ]
 [-0.5963377 ]
 [-1.1194146 ]
 [-1.5850015 ]]
89 Cost:  1.4001408 
Prediction:
 [[ 0.414711  ]
 [-0.51066864]
 [-0.5699264 ]
 [-0.6953031 ]
 [-0.49028516]
 [-0.5962982 ]
 [-1.1193861 ]
 [-1.5849725 ]]
90 Cost:  1.400051 
Prediction:
 [[ 0.41476262]
 [-0.5106155 ]
 [-0.5698819 ]
 [-0.6952683 ]
 [-0.49024463]
 [-0.5962587 ]
 [-1.1193577 ]
 [-1.5849437 ]]
91 Cost:  1.3999612 
Prediction:
 [[ 0.4148141 ]
 [-0.51056254]
 [-0.5698374 ]
 [-0.69523346]
 [-0.49020392]
 [-0.59621924]
 [-1.1193293 ]
 [-1.5849147 ]]
92 Cost:  1.3998715 
Prediction:
 [[ 0.4148656 ]
 [-0.5105094 ]
 [-0.569793  ]
 [-0.69519866]
 [-0.49016333]
 [-0.5961798 ]
 [-1.1193008 ]
 [-1.5848858 ]]
93 Cost:  1.3997818 
Prediction:
 [[ 0.41491723]
 [-0.5104564 ]
 [-0.56

 [-1.5799917 ]]
263 Cost:  1.3846405 
Prediction:
 [[ 0.4236399 ]
 [-0.50147384]
 [-0.5622211 ]
 [-0.6892754 ]
 [-0.48324484]
 [-0.58945733]
 [-1.1144639 ]
 [-1.579963  ]]
264 Cost:  1.384552 
Prediction:
 [[ 0.42369115]
 [-0.5014211 ]
 [-0.56217694]
 [-0.6892408 ]
 [-0.48320442]
 [-0.58941805]
 [-1.1144357 ]
 [-1.5799341 ]]
265 Cost:  1.3844633 
Prediction:
 [[ 0.4237424 ]
 [-0.50136834]
 [-0.5621327 ]
 [-0.6892062 ]
 [-0.48316395]
 [-0.58937883]
 [-1.1144074 ]
 [-1.5799054 ]]
266 Cost:  1.3843746 
Prediction:
 [[ 0.42379367]
 [-0.5013156 ]
 [-0.56208855]
 [-0.6891716 ]
 [-0.4831236 ]
 [-0.58933955]
 [-1.1143792 ]
 [-1.5798767 ]]
267 Cost:  1.3842862 
Prediction:
 [[ 0.4238447 ]
 [-0.5012629 ]
 [-0.5620443 ]
 [-0.68913704]
 [-0.48308325]
 [-0.5893004 ]
 [-1.1143509 ]
 [-1.5798479 ]]
268 Cost:  1.3841975 
Prediction:
 [[ 0.42389596]
 [-0.5012102 ]
 [-0.56200016]
 [-0.6891025 ]
 [-0.4830429 ]
 [-0.5892612 ]
 [-1.1143227 ]
 [-1.5798192 ]]
269 Cost:  1.3841089 
Prediction:
 [[ 0.42394722]

441 Cost:  1.3689895 
Prediction:
 [[ 0.4327134 ]
 [-0.49212813]
 [-0.5543896 ]
 [-0.68314904]
 [-0.47608912]
 [-0.58250415]
 [-1.1094602 ]
 [-1.5748696 ]]
442 Cost:  1.3689024 
Prediction:
 [[ 0.43276393]
 [-0.49207592]
 [-0.55434585]
 [-0.6831149 ]
 [-0.47604913]
 [-0.5824653 ]
 [-1.1094323 ]
 [-1.5748411 ]]
443 Cost:  1.3688152 
Prediction:
 [[ 0.43281472]
 [-0.4920236 ]
 [-0.55430204]
 [-0.6830806 ]
 [-0.47600913]
 [-0.58242655]
 [-1.1094043 ]
 [-1.5748127 ]]
444 Cost:  1.3687282 
Prediction:
 [[ 0.43286526]
 [-0.4919715 ]
 [-0.5542583 ]
 [-0.68304634]
 [-0.4759692 ]
 [-0.5823876 ]
 [-1.1093764 ]
 [-1.5747843 ]]
445 Cost:  1.3686409 
Prediction:
 [[ 0.43291605]
 [-0.49191922]
 [-0.5542146 ]
 [-0.6830122 ]
 [-0.47592926]
 [-0.5823488 ]
 [-1.1093484 ]
 [-1.5747558 ]]
446 Cost:  1.3685538 
Prediction:
 [[ 0.4329666 ]
 [-0.49186695]
 [-0.55417085]
 [-0.6829779 ]
 [-0.4758892 ]
 [-0.58230996]
 [-1.1093204 ]
 [-1.5747273 ]]
447 Cost:  1.3684666 
Prediction:
 [[ 0.43301737]
 [-0.4918148 ]

619 Cost:  1.3535547 
Prediction:
 [[ 0.44171548]
 [-0.4828508 ]
 [-0.54661524]
 [-0.6770671 ]
 [-0.46898615]
 [-0.57560205]
 [-1.1044906 ]
 [-1.5698094 ]]
620 Cost:  1.3534687 
Prediction:
 [[ 0.4417658 ]
 [-0.4827988 ]
 [-0.5465716 ]
 [-0.67703307]
 [-0.46894634]
 [-0.5755634 ]
 [-1.1044627 ]
 [-1.5697812 ]]
621 Cost:  1.3533826 
Prediction:
 [[ 0.4418161 ]
 [-0.4827469 ]
 [-0.54652816]
 [-0.6769991 ]
 [-0.46890652]
 [-0.57552475]
 [-1.104435  ]
 [-1.5697528 ]]
622 Cost:  1.3532965 
Prediction:
 [[ 0.44186652]
 [-0.48269498]
 [-0.54648465]
 [-0.676965  ]
 [-0.46886677]
 [-0.57548606]
 [-1.1044072 ]
 [-1.5697246 ]]
623 Cost:  1.3532102 
Prediction:
 [[ 0.44191694]
 [-0.482643  ]
 [-0.5464411 ]
 [-0.6769309 ]
 [-0.468827  ]
 [-0.57544744]
 [-1.1043794 ]
 [-1.5696962 ]]
624 Cost:  1.3531243 
Prediction:
 [[ 0.44196737]
 [-0.48259115]
 [-0.54639757]
 [-0.6768969 ]
 [-0.46878725]
 [-0.5754089 ]
 [-1.1043515 ]
 [-1.5696679 ]]
625 Cost:  1.3530381 
Prediction:
 [[ 0.4420178 ]
 [-0.48253912]

795 Cost:  1.338491 
Prediction:
 [[ 0.45055652]
 [-0.47373676]
 [-0.5389775 ]
 [-0.6710919 ]
 [-0.462008  ]
 [-0.56882113]
 [-1.0996068 ]
 [-1.5648361 ]]
796 Cost:  1.338406 
Prediction:
 [[ 0.45060647]
 [-0.47368526]
 [-0.53893423]
 [-0.67105806]
 [-0.46196854]
 [-0.56878275]
 [-1.0995791 ]
 [-1.564808  ]]
797 Cost:  1.338321 
Prediction:
 [[ 0.45065653]
 [-0.47363365]
 [-0.5388911 ]
 [-0.6710242 ]
 [-0.46192896]
 [-0.5687443 ]
 [-1.0995514 ]
 [-1.5647799 ]]
798 Cost:  1.3382361 
Prediction:
 [[ 0.4507066 ]
 [-0.4735821 ]
 [-0.5388478 ]
 [-0.67099047]
 [-0.46188956]
 [-0.5687059 ]
 [-1.0995238 ]
 [-1.5647517 ]]
799 Cost:  1.338151 
Prediction:
 [[ 0.45075667]
 [-0.47353053]
 [-0.5388046 ]
 [-0.6709566 ]
 [-0.4618501 ]
 [-0.5686676 ]
 [-1.0994961 ]
 [-1.5647235 ]]
800 Cost:  1.3380661 
Prediction:
 [[ 0.45080662]
 [-0.47347885]
 [-0.5387613 ]
 [-0.67092276]
 [-0.4618106 ]
 [-0.5686292 ]
 [-1.0994685 ]
 [-1.5646954 ]]
801 Cost:  1.3379811 
Prediction:
 [[ 0.4508567 ]
 [-0.47342718]
 [-

973 Cost:  1.3234553 
Prediction:
 [[ 0.45943618]
 [-0.46458006]
 [-0.53130376]
 [-0.6650883 ]
 [-0.4549973 ]
 [-0.56200814]
 [-1.0946982 ]
 [-1.5598367 ]]
974 Cost:  1.3233714 
Prediction:
 [[ 0.4594859 ]
 [-0.4645288 ]
 [-0.53126085]
 [-0.6650547 ]
 [-0.45495802]
 [-0.5619699 ]
 [-1.0946708 ]
 [-1.5598087 ]]
975 Cost:  1.3232875 
Prediction:
 [[ 0.4595356 ]
 [-0.46447754]
 [-0.5312179 ]
 [-0.66502106]
 [-0.45491874]
 [-0.5619317 ]
 [-1.0946432 ]
 [-1.5597808 ]]
976 Cost:  1.3232034 
Prediction:
 [[ 0.4595853 ]
 [-0.46442622]
 [-0.5311749 ]
 [-0.66498744]
 [-0.4548794 ]
 [-0.5618936 ]
 [-1.0946157 ]
 [-1.5597527 ]]
977 Cost:  1.3231196 
Prediction:
 [[ 0.45963526]
 [-0.4643749 ]
 [-0.5311319 ]
 [-0.6649538 ]
 [-0.45484012]
 [-0.5618554 ]
 [-1.0945883 ]
 [-1.5597248 ]]
978 Cost:  1.3230357 
Prediction:
 [[ 0.45968497]
 [-0.46432364]
 [-0.53108895]
 [-0.6649202 ]
 [-0.45480096]
 [-0.5618173 ]
 [-1.0945607 ]
 [-1.5596968 ]]
979 Cost:  1.3229518 
Prediction:
 [[ 0.45973468]
 [-0.46427238]

 [-1.5553131 ]]
1136 Cost:  1.3098658 
Prediction:
 [[ 0.467507  ]
 [-0.45625252]
 [-0.5243246 ]
 [-0.65962744]
 [-0.44862127]
 [-0.55581164]
 [-1.090231  ]
 [-1.5552853 ]]
1137 Cost:  1.309783 
Prediction:
 [[ 0.46755648]
 [-0.45620155]
 [-0.5242819 ]
 [-0.659594  ]
 [-0.4485823 ]
 [-0.5557738 ]
 [-1.0902036 ]
 [-1.5552574 ]]
1138 Cost:  1.3097001 
Prediction:
 [[ 0.46760595]
 [-0.4561506 ]
 [-0.5242393 ]
 [-0.65956056]
 [-0.44854325]
 [-0.5557358 ]
 [-1.0901762 ]
 [-1.5552297 ]]
1139 Cost:  1.3096172 
Prediction:
 [[ 0.46765518]
 [-0.45609963]
 [-0.5241965 ]
 [-0.6595272 ]
 [-0.4485042 ]
 [-0.5556979 ]
 [-1.0901489 ]
 [-1.5552018 ]]
1140 Cost:  1.3095343 
Prediction:
 [[ 0.46770465]
 [-0.4560488 ]
 [-0.5241538 ]
 [-0.6594938 ]
 [-0.44846517]
 [-0.55566   ]
 [-1.0901216 ]
 [-1.5551739 ]]
1141 Cost:  1.3094515 
Prediction:
 [[ 0.467754  ]
 [-0.45599782]
 [-0.52411115]
 [-0.65946037]
 [-0.4484262 ]
 [-0.5556221 ]
 [-1.0900942 ]
 [-1.5551461 ]]
1142 Cost:  1.3093686 
Prediction:
 [[ 0.46

1301 Cost:  1.296272 
Prediction:
 [[ 0.47563028]
 [-0.44787085]
 [-0.5173001 ]
 [-0.65413123]
 [-0.44220376]
 [-0.5495748 ]
 [-1.0857345 ]
 [-1.5507044 ]]
1302 Cost:  1.2961903 
Prediction:
 [[ 0.47567928]
 [-0.44782025]
 [-0.5172577 ]
 [-0.65409803]
 [-0.44216502]
 [-0.5495372 ]
 [-1.0857073 ]
 [-1.5506767 ]]
1303 Cost:  1.2961085 
Prediction:
 [[ 0.47572827]
 [-0.44776964]
 [-0.51721525]
 [-0.65406483]
 [-0.44212627]
 [-0.5494995 ]
 [-1.0856801 ]
 [-1.5506489 ]]
1304 Cost:  1.2960265 
Prediction:
 [[ 0.47577727]
 [-0.44771904]
 [-0.5171728 ]
 [-0.65403163]
 [-0.44208753]
 [-0.54946184]
 [-1.085653  ]
 [-1.5506213 ]]
1305 Cost:  1.2959447 
Prediction:
 [[ 0.47582638]
 [-0.44766843]
 [-0.51713043]
 [-0.65399843]
 [-0.44204867]
 [-0.5494242 ]
 [-1.0856258 ]
 [-1.5505936 ]]
1306 Cost:  1.2958628 
Prediction:
 [[ 0.47587538]
 [-0.44761783]
 [-0.517088  ]
 [-0.65396523]
 [-0.44200993]
 [-0.5493864 ]
 [-1.0855986 ]
 [-1.5505658 ]]
1307 Cost:  1.2957809 
Prediction:
 [[ 0.47592437]
 [-0.447

1468 Cost:  1.2826899 
Prediction:
 [[ 0.48378992]
 [-0.4394461 ]
 [-0.5102389 ]
 [-0.64860547]
 [-0.4357531 ]
 [-0.54330546]
 [-1.0812111 ]
 [-1.5460943 ]]
1469 Cost:  1.282609 
Prediction:
 [[ 0.48383868]
 [-0.4393958 ]
 [-0.51019675]
 [-0.64857244]
 [-0.43571454]
 [-0.543268  ]
 [-1.081184  ]
 [-1.5460668 ]]
1470 Cost:  1.282528 
Prediction:
 [[ 0.48388743]
 [-0.43934536]
 [-0.5101545 ]
 [-0.6485394 ]
 [-0.43567598]
 [-0.5432305 ]
 [-1.081157  ]
 [-1.5460391 ]]
1471 Cost:  1.2824471 
Prediction:
 [[ 0.4839362 ]
 [-0.43929505]
 [-0.5101123 ]
 [-0.64850634]
 [-0.4356374 ]
 [-0.54319304]
 [-1.08113   ]
 [-1.5460116 ]]
1472 Cost:  1.2823663 
Prediction:
 [[ 0.48398495]
 [-0.43924475]
 [-0.5100701 ]
 [-0.6484733 ]
 [-0.43559885]
 [-0.54315555]
 [-1.081103  ]
 [-1.545984  ]]
1473 Cost:  1.2822853 
Prediction:
 [[ 0.4840337 ]
 [-0.43919432]
 [-0.5100279 ]
 [-0.64844036]
 [-0.43556023]
 [-0.5431181 ]
 [-1.0810759 ]
 [-1.5459565 ]]
1474 Cost:  1.2822044 
Prediction:
 [[ 0.48408246]
 [-0.4391

1632 Cost:  1.269511 
Prediction:
 [[ 0.4917556 ]
 [-0.4312203 ]
 [-0.50334466]
 [-0.64321065]
 [-0.42945504]
 [-0.53718424]
 [-1.0767944 ]
 [-1.5415927 ]]
1633 Cost:  1.2694311 
Prediction:
 [[ 0.49180388]
 [-0.43117034]
 [-0.50330275]
 [-0.64317787]
 [-0.42941678]
 [-0.5371471 ]
 [-1.0767676 ]
 [-1.5415653 ]]
1634 Cost:  1.2693514 
Prediction:
 [[ 0.4918524 ]
 [-0.4311204 ]
 [-0.50326097]
 [-0.6431451 ]
 [-0.42937845]
 [-0.53711   ]
 [-1.0767407 ]
 [-1.541538  ]]
1635 Cost:  1.2692714 
Prediction:
 [[ 0.49190068]
 [-0.43107045]
 [-0.503219  ]
 [-0.6431123 ]
 [-0.42934018]
 [-0.53707266]
 [-1.0767138 ]
 [-1.5415106 ]]
1636 Cost:  1.2691917 
Prediction:
 [[ 0.49194896]
 [-0.4310205 ]
 [-0.50317717]
 [-0.6430795 ]
 [-0.42930192]
 [-0.5370355 ]
 [-1.076687  ]
 [-1.5414832 ]]
1637 Cost:  1.2691119 
Prediction:
 [[ 0.49199736]
 [-0.43097055]
 [-0.5031353 ]
 [-0.64304674]
 [-0.4292637 ]
 [-0.5369983 ]
 [-1.07666   ]
 [-1.5414557 ]]
1638 Cost:  1.269032 
Prediction:
 [[ 0.49204576]
 [-0.4309

1798 Cost:  1.2563403 
Prediction:
 [[ 0.4997599 ]
 [-0.4229504 ]
 [-0.496413  ]
 [-0.63778585]
 [-0.42312294]
 [-0.5310298 ]
 [-1.0723509 ]
 [-1.5370624 ]]
1799 Cost:  1.2562613 
Prediction:
 [[ 0.49980807]
 [-0.42290068]
 [-0.49637127]
 [-0.63775325]
 [-0.42308486]
 [-0.53099275]
 [-1.0723242 ]
 [-1.5370351 ]]
1800 Cost:  1.2561824 
Prediction:
 [[ 0.499856  ]
 [-0.4228509 ]
 [-0.49632955]
 [-0.6377206 ]
 [-0.42304677]
 [-0.5309558 ]
 [-1.0722975 ]
 [-1.5370078 ]]
1801 Cost:  1.2561035 
Prediction:
 [[ 0.49990416]
 [-0.42280126]
 [-0.49628794]
 [-0.637688  ]
 [-0.42300868]
 [-0.5309187 ]
 [-1.0722706 ]
 [-1.5369806 ]]
1802 Cost:  1.2560246 
Prediction:
 [[ 0.49995232]
 [-0.4227515 ]
 [-0.49624628]
 [-0.6376554 ]
 [-0.42297065]
 [-0.53088176]
 [-1.0722439 ]
 [-1.5369533 ]]
1803 Cost:  1.2559456 
Prediction:
 [[ 0.5000005 ]
 [-0.42270172]
 [-0.4962046 ]
 [-0.6376227 ]
 [-0.42293257]
 [-0.5308447 ]
 [-1.0722172 ]
 [-1.536926  ]]
1804 Cost:  1.2558666 
Prediction:
 [[ 0.50004864]
 [-0.42

1972 Cost:  1.2427068 
Prediction:
 [[ 0.50809526]
 [-0.41433585]
 [-0.4891923 ]
 [-0.6321347 ]
 [-0.4165269 ]
 [-0.5246185 ]
 [-1.0677207 ]
 [-1.532341  ]]
1973 Cost:  1.2426288 
Prediction:
 [[ 0.5081432 ]
 [-0.41428643]
 [-0.48915088]
 [-0.63210225]
 [-0.41648912]
 [-0.52458173]
 [-1.0676941 ]
 [-1.532314  ]]
1974 Cost:  1.2425508 
Prediction:
 [[ 0.5081909 ]
 [-0.41423714]
 [-0.48910952]
 [-0.6320698 ]
 [-0.41645133]
 [-0.52454495]
 [-1.0676675 ]
 [-1.5322869 ]]
1975 Cost:  1.2424731 
Prediction:
 [[ 0.5082387 ]
 [-0.41418773]
 [-0.48906815]
 [-0.6320374 ]
 [-0.41641355]
 [-0.5245083 ]
 [-1.0676409 ]
 [-1.5322597 ]]
1976 Cost:  1.2423952 
Prediction:
 [[ 0.5082865 ]
 [-0.41413844]
 [-0.48902667]
 [-0.63200504]
 [-0.41637576]
 [-0.5244715 ]
 [-1.0676143 ]
 [-1.5322326 ]]
1977 Cost:  1.2423172 
Prediction:
 [[ 0.50833416]
 [-0.41408896]
 [-0.48898536]
 [-0.6319726 ]
 [-0.41633785]
 [-0.52443475]
 [-1.0675877 ]
 [-1.5322056 ]]
1978 Cost:  1.2422392 
Prediction:
 [[ 0.50838184]
 [-0.41