In [19]:
import numpy as np
import tensorflow as tf

In [20]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [24]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name ='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name ='bias')


# tf.nn.softmax computes softmax activations
# softmax =exp(Logits) / reduce_sum(exp(Logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W)+ b)

# Cross Entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer =tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

#launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
            
            
            print('--------------')
            
            # Testing & One-hot encoding
            a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
            print(a, sess.run(tf.argmax(a, 1)))

            print('--------------')
            b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
            print(b, sess.run(tf.argmax(b, 1)))

            print('--------------')
            c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
            print(c, sess.run(tf.argmax(c, 1)))

            print('--------------')
            all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
            print(all, sess.run(tf.argmax(all, 1)))

0 1.8032937
--------------
[[9.7134113e-01 1.4757026e-06 2.8657302e-02]] [0]
--------------
[[0.6865233  0.16005136 0.15342528]] [0]
--------------
[[0.50337046 0.13238077 0.36424872]] [0]
--------------
[[9.7134113e-01 1.4757026e-06 2.8657302e-02]
 [6.8652332e-01 1.6005136e-01 1.5342528e-01]
 [5.0337046e-01 1.3238077e-01 3.6424872e-01]] [0 0 0]
200 0.6520511
--------------
[[9.9093705e-01 8.1723034e-03 8.9074549e-04]] [0]
--------------
[[0.56916195 0.28682333 0.14401475]] [0]
--------------
[[0.01577802 0.04039824 0.9438237 ]] [2]
--------------
[[9.9093705e-01 8.1723034e-03 8.9074549e-04]
 [5.6916195e-01 2.8682333e-01 1.4401475e-01]
 [1.5778022e-02 4.0398244e-02 9.4382370e-01]] [0 0 2]
400 0.5425943
--------------
[[9.6376616e-01 3.5852384e-02 3.8139831e-04]] [0]
--------------
[[0.6590685  0.23413576 0.10679576]] [0]
--------------
[[0.00145505 0.01894859 0.9795964 ]] [2]
--------------
[[9.6376616e-01 3.5852384e-02 3.8139833e-04]
 [6.5906852e-01 2.3413575e-01 1.0679576e-01]
 [1.45